openapi: 3.0.0
servers:
  - description: Première partie du projet Hackaton Login 2024
    url: https://github.com/RoryMaillard/Hackathon
info:
  version: "1.0.0"
  title: Event API
  description: APIs des évènements culturels de Nantes
paths:
  /listactivities:
    get:
      tags:
        - Users
      description: Retourne la liste des évènements culturels disponibles
      operationId: get_all_activites
      responses:
        '200':
          description: Tous les évènements
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

  /activity/<id>/<date>:
    get:
      tags:
        - Users
      description: Retourne les évènements par id et date
      operationId: get_activity_by_id_date
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: date
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Evènements par id et date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /activity/<id>:
    get:
      tags:
        - Users
      description: Retourne les évènements par id
      operationId: get_activity_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32

      responses:
        '200':
          description: Evènements par id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /categories:
    post:
      tags:
        - Users
      description: Retourne les évènements filtrés par la liste de catégories fournie dans le corps
      operationId: get_categories_filter
      requestBody:
        content:
          application/json:
            schema:
              type: array,
              items:
                type: string
      responses:
        '200':
          description: Evènements filtrés par catégorie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'


  /allcategories:
    get:
      tags:
        - Users
      description: Retourne les catégories d'évènements disponibles
      operationId: get_all_categories
      responses:
        '200':
          description: Toutes les catégories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    Event:
      type: object
      properties:
        accueil_enfant:
          type: string
        adresse:
          type: string
        annule:
          type: string
        categorie_1:
          type: string
        categorie_2:
          type: string
        categorie_3:
          type: string
        categorie_4:
          type: string
        categorie_5:
          type: string
        code_postal:
          type: string
        complet:
          type: string
        date:
          type: string
        date_report:
          type: string
        description:
          type: string
        emetteur:
          type: string
        gratuit:
          type: string
        heure_debut:
          type: string
        heure_fin:
          type: string
        id_manif:
          type: string
        libelle_courriel:
          type: string
        libelle_site:
          type: string
        libelle_telephone:
          type: string
        lien_agenda:
          type: string
        lieu:
          type: string
        lieu_quartier:
          type: string
        lieu_siteweb:
          type: string
        lieu_tel:
          type: string
        media_url:
          type: string
        nom:
          type: string
        organisateurs:
          type: string
        precisions_public:
          type: string
        reporte:
          type: string
        rubrique:
          type: string
        telephone:
          type: string
        url_site:
          type: string
        ville:
          type: string
      description: Evènement culturel